# Generated by Django 5.1.1 on 2024-09-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('certificate_type', models.CharField(max_length=100)),
                ('subscription_period', models.CharField(max_length=100)),
                ('certificate_issued', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('auto_renew', models.CharField(max_length=10)),
                ('lock', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('privacy', models.CharField(max_length=10)),
                ('nameservers', models.TextField()),
                ('estimated_value', models.CharField(max_length=50)),
                ('create_date', models.DateField()),
                ('renewal_price', models.CharField(max_length=50)),
                ('protection_plan', models.CharField(max_length=50)),
                ('ownership_date', models.DateField()),
            ],
        ),
    ]
