# Generated by Django 5.1.2 on 2024-11-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_brand_category_model_series_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(default='', max_length=500),
        ),
    ]
