# Generated by Django 5.1.2 on 2024-11-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_inventory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='status',
            new_name='status_i',
        ),
    ]
