# Generated by Django 5.1.2 on 2024-11-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_status_inventory_status_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status_i',
            field=models.CharField(default='Available', max_length=5000),
        ),
    ]
