# Generated by Django 5.1.2 on 2024-11-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_inventory_status_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='status_i',
            new_name='status',
        ),
    ]
